// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXb_D7G_8eYMS8MX8tRyqXZ-mRj0LoCso',
    appId: '1:168255024061:web:e78736a3de0eae81ed80d4',
    messagingSenderId: '168255024061',
    projectId: 'cargaliberada-edab3',
    authDomain: 'cargaliberada-edab3.firebaseapp.com',
    storageBucket: 'cargaliberada-edab3.firebasestorage.app',
    measurementId: 'G-9M9R2Q6MPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqoxo2ImJTS9pdEdPfPVzZHdt6QDBcwr4',
    appId: '1:168255024061:android:65489cc8bafd1eefed80d4',
    messagingSenderId: '168255024061',
    projectId: 'cargaliberada-edab3',
    storageBucket: 'cargaliberada-edab3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr8prrkmfCIDdauXNc7776A1I3DslJsEg',
    appId: '1:168255024061:ios:8d50d40e070259b5ed80d4',
    messagingSenderId: '168255024061',
    projectId: 'cargaliberada-edab3',
    storageBucket: 'cargaliberada-edab3.firebasestorage.app',
    iosClientId: '168255024061-vhk50vbjp787198pmsie49h0lfo815j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cargaliberada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr8prrkmfCIDdauXNc7776A1I3DslJsEg',
    appId: '1:168255024061:ios:8d50d40e070259b5ed80d4',
    messagingSenderId: '168255024061',
    projectId: 'cargaliberada-edab3',
    storageBucket: 'cargaliberada-edab3.firebasestorage.app',
    iosClientId: '168255024061-vhk50vbjp787198pmsie49h0lfo815j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cargaliberada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXb_D7G_8eYMS8MX8tRyqXZ-mRj0LoCso',
    appId: '1:168255024061:web:371bb7fd64077601ed80d4',
    messagingSenderId: '168255024061',
    projectId: 'cargaliberada-edab3',
    authDomain: 'cargaliberada-edab3.firebaseapp.com',
    storageBucket: 'cargaliberada-edab3.firebasestorage.app',
    measurementId: 'G-ZCGSZH16N1',
  );
}
